defaults: &defaults
  secret_key_base: ecbae5de81aae202f6b859737f2072f45202aea4f6ddb7617a6522e0f57219d5f47da407d76a3a1b72ac61e6d6a9077f0bdebd9cdefa6cca0a678dc3ac711f3c
  bugsnag_api_key: ''
  google_api_key: ''

development:
  <<: *defaults
production:
  <<: *defaults
test:
  <<: *defaults
